### PR TITLE
Fix: multiple matrices can be applied for same prime in homomorphic dft

### LINKED ISSUE #561: Bug: homomorphic DFT correctness error when decomposition level has multiple matrices for a single prime
This bug is at the origin of https://github.com/tuneinsight/lattigo/discussions/560

## Cause

https://github.com/tuneinsight/lattigo/blob/c930849f741895887789a3e2df068042b58be9d6/circuits/ckks/dft/dft.go#L343

```Go
// dft evaluates a series of [lintrans.LinearTransformation] sequentially on the ctIn and stores the result in opOut.
func (eval *Evaluator) dft(ctIn *rlwe.Ciphertext, matrices []ltcommon.LinearTransformation, opOut *rlwe.Ciphertext) (err error) {

	inputLogSlots := ctIn.LogDimensions

	// Sequentially multiplies w with the provided dft matrices.
	if err = eval.LTEvaluator.EvaluateSequential(ctIn, matrices, opOut); err != nil {
		return
	}

	// Encoding matrices are a special case of `fractal` linear transform
	// that doesn't change the underlying plaintext polynomial Y = X^{N/n}
	// of the input ciphertext.
	opOut.LogDimensions = inputLogSlots

	return
}
```

Does not take into account that multiples matrices can be evaluated for a single prime. 

## Fix
Algorithm shouldn't call EvaluateSequential, but sequentially evaluate each matrice and only rescale after all the matrices of a same level have been evaluated (this can be derived from the `Level` field of `MatrixLiteral`).

### PR DESCRIPTION
**Pull request by lehugueni**
Fix #561 as described in the issue. The bug was raised in #560. 

Added a test checking correctness of the bootstrapping for all default parameters. Not run by default, but only with `-allparams` flag.

### CODE REVIEW

**Review by MGeorgie — APPROVED** [review]
oki

File: circuits/ckks/bootstrapping/default_parameters.go [hunk 1]
```diff
@@ -181,6 +181,7 @@ var (
 	N15QP880H16384H32 = defaultParametersLiteral{
 		ckks.ParametersLiteral{
 			LogN:            15,
+			LogNthRoot:      17,
```
Comment (Pro7ech) [inline circuits/ckks/bootstrapping/default_parameters.go:184]: Why is 4N = 1 mod Q necessary here?

Comment (lehugueni) [reply circuits/ckks/bootstrapping/default_parameters.go:184]: Because this only sets the value `LogN` for the residual parameters, but the `LogN'` of the bootstrapping parameters will be the default one (i.e. `16`) and we need `Q = 1 mod 2N'`.

Comment (Pro7ech) [reply circuits/ckks/bootstrapping/default_parameters.go:184]: But the residual paramters for this set are expected to have LogN=15 too, so I dont' see why LogNthRoot should be hardcoded to 17 for default parameters (it's ok to manually set it though, but I think that for default it shouldn't). Is it because the tests fix LogN to 16? Why not derive it from the bootstrapping parameters?

Comment (lehugueni) [reply circuits/ckks/bootstrapping/default_parameters.go:184]: Yes, the residual parameters will have LogN=15 but the bootstrapping params will have LogN=16 so we need to generate the primes accordingly. It all follows from the implementation of `NewParametersFromLiteral` and its doc: https://github.com/tuneinsight/lattigo/blob/5fc229b046cbba8ccbc00dd528af50e9de2307d5/circuits/ckks/bootstrapping/parameters.go#L46

Comment (Pro7ech) [reply circuits/ckks/bootstrapping/default_parameters.go:184]: But is a set for Logn=15

Comment (Pro7ech) [reply circuits/ckks/bootstrapping/default_parameters.go:184]: Ok, I understand the confusion. These default parameters are from the papers and are expecting LogN residual parameters to be equal to LogN bootstrapping parameters. Of course you can accommodate the parameters for other ring degree, but these are not the "default" ones anymore (refering to the papers) and will not reproduce exactly the moduli chain used for the experiments.
